packages:
  - "ai"
  - "federation"
  - "models"
  - "web-next"

catalog:
  "@c4spar/mock-fetch": "jsr:^1.0.0"
  "@fedify/fedify": "jsr:2.1.5"
  "@fedify/markdown-it-hashtag": "jsr:^0.3.0"
  "@fedify/markdown-it-mention": "jsr:^0.3.0"
  "@fedify/vocab": "jsr:2.1.5"
  "@hackerspub/markdown-it-texmath": "^1.0.1"
  "@logtape/logtape": "jsr:2.0.6"
  "@mdit-vue/plugin-title": "^2.1.4"
  "@opentelemetry/api": "^1.0.15"
  "@searking/markdown-it-cjk-breaks": "2.0.1-0"
  "@shikijs/markdown-it": "^3.23.0"
  "@shikijs/transformers": "^3.23.0"
  "@simplewebauthn/browser": "jsr:^13.1.0"
  "@simplewebauthn/server": "jsr:^13.3.0"
  "@std/assert": "jsr:^1.0.19"
  "@std/async": "jsr:^1.2.0"
  "@std/collections": "jsr:^1.1.6"
  "@std/encoding": "jsr:^1.0.10"
  "@std/html": "jsr:^1.0.5"
  "@std/text": "jsr:^1.0.17"
  "@std/uuid": "jsr:^1.1.0"
  "@vertana/context-web": "^0.1.1"
  "@vertana/core": "jsr:^0.1.1"
  "@vertana/facade": "jsr:^0.1.1"
  "ai": "^6.0.146"
  "apns2": "^12.2.0"
  "arcsecond": "^5.0.0"
  "cheerio": "^1.2.0"
  "cssfilter": "^0.0.11"
  "drizzle-orm": "1.0.0-beta.1-5e64efc"
  "fluent-ffmpeg": "^2.1.3"
  "flydrive": "^1.3.0"
  "iconv-lite": "^0.6.3"
  "katex": "^0.16.44"
  "keyv": "^5.6.0"
  "markdown-it-abbr": "^2.0.0"
  "markdown-it-anchor": "^9.2.0"
  "markdown-it-async": "^2.2.0"
  "markdown-it-deflist": "^3.0.0"
  "markdown-it-footnote": "^4.0.0"
  "markdown-it-github-alerts": "^0.3.2"
  "markdown-it-graphviz": "^1.1.2"
  "markdown-it-toc-done-right": "^4.2.0"
  "open-graph-scraper": "^6.11.0"
  "pdf-lib": "^1.17.1"
  "postgres": "^3.4.8"
  "sharp": "^0.33.5"
  "shiki": "^3.23.0"
  "ssrfcheck": "^1.3.0"
  "tinyld": "^1.3.4"
  "xss": "^1.0.15"
